[versions]
# Gradle
androidGradlePlugin = "8.7.3"

# Android
compileSdk = "35"
targetSdk = "35"
minSdk = "24"

# Kotlin
kotlin = "2.0.21"
java = "18"
ksp = "2.0.21-1.0.27"
coroutines = "1.9.0"

# AndroidX
androidx-core-coreKtx = "1.15.0"
androidx-appcompat = "1.7.0"
androidx-lifecycle = "2.8.7"

# Compose
compose-bom = "2024.11.00" # https://developer.android.com/jetpack/compose/bom/bom-mapping
# version of Compose compiler is determined by plugin "org.jetbrains.kotlin.plugin.compose" and is using Kotlin version
# see: https://developer.android.com/develop/ui/compose/compiler

# Dagger & Hilt
hilt = "2.50"
hiltNavigationCompose = "1.2.0"

# Remote
retrofit-library = "2.9.0"
retrofit-moshi = "2.7.0"
okhttp3-loggingInterceptor = "4.8.0"

# Local
room = "2.6.1"
dataStore-preferences = "1.1.1"

# Testing
junit = "5.11.4"
mockk = "1.13.3"
kotestAssertions = "5.5.5"

# Misc (preserve alphabetical order)
jakewhartonTimber = "5.0.1"
mmolosayDebounce = "1.2.0"
valentinilkShimmer = "1.2.0"